from django.core.management.base import BaseCommand
from core.models import Post

class Command(BaseCommand):
    help = 'Displays current time'

    def handle(self, *args, **kwargs):
        Post.objects.all().delete()

        objects_to_create = [
            Post(category='Cosplay', title='Rabit', image='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStKh8wiW72nz0EIhel3rFD0hSBGAXC-HtgFgDzFlFTykPvRCV7T1t3PTgEYP_2Oxku7QQ&usqp=CAU', content=''),
            Post(category='Cosplay', title='Cat', image='https://i.ebayimg.com/images/g/p08AAOSw~Etk3f7l/s-l500.jpg', content=''),
            Post(category='Cosplay', title='Fox', image='https://m.media-amazon.com/images/I/614uIvcKnOL._AC_SX679_.jpg', content=''),
            Post(category='Cosplay', title='China', image='http://m.china-cart.com/u/153/734525/anime_cosplay.jpg', content=''),
            Post(category='Cosplay', title='Halloween', image='https://m.media-amazon.com/images/I/71A1oB8Ze1L._AC_SX679_.jpg', content=''),
            Post(category='Cosplay', title='Angel', image='https://m.media-amazon.com/images/I/71Kix1VXhML._SX679_.jpg', content=''),
            Post(category='Cosplay', title='Jenny', image='https://assets.vogue.in/photos/635ab762e1b72bfa41382722/2:3/w_2240,c_limit/Jennie%20Kim%20fitness%20lessons.jpg', content=''),

            Post(category='Bodysuit', title='title', image='https://down-my.img.susercontent.com/file/sg-11134201-7qvee-liu072oxe1ome2', content=''),
            Post(category='Bodysuit', title='Wear with niple', image='https://down-my.img.susercontent.com/file/my-11134207-7r992-lmcoev6739ueb3', content=''),
            Post(category='Bodysuit', title='title', image='https://down-my.img.susercontent.com/file/6206da488cbe582c4a85746e3cf9aa03', content=''),
            Post(category='Bodysuit', title='title', image='https://down-my.img.susercontent.com/file/54a512dc9d7a95af622b0b920f3bfa30', content=''),
            Post(category='Bodysuit', title='title', image='https://down-my.img.susercontent.com/file/ae5ac4e8c0689d8c33ba9ccba955e71a_tn', content=''),
            Post(category='Bodysuit', title='title', image='https://down-my.img.susercontent.com/file/0104eb888fef8c5ea71de0e1b6b54578_tn', content=''),
            Post(category='Bodysuit', title='title', image='https://down-my.img.susercontent.com/file/d005bd79198d64a1cb4edf0f16349f8c_tn', content=''),
            Post(category='Bodysuit', title='title', image='https://down-my.img.susercontent.com/file/e1b347d337aaac57a4af182cf0770f0e_tn', content=''),
            Post(category='Bodysuit', title='title', image='https://down-my.img.susercontent.com/file/d43f5c7f8480ddf949ccfa19f720de59_tn', content=''),


            # Post(category='Chip', title='title', image='https://shopee.com.my/user/purchase/order/153283957270889?type=8', content=''),
            # Post(category='Chip', title='title', image='https://shopee.com.my/user/purchase/order/153166326226530?type=8', content=''),
            # Post(category='Chip', title='title', image='https://down-my.img.susercontent.com/file/sg-11134201-7qveh-lf0xewm13wofdc_tn', content=''),
            # Post(category='Chip', title='title', image='https://shopee.com.my/user/purchase/order/152543437209461?type=8', content=''),
            # Post(category='Chip', title='title', image='https://shopee.com.my/user/purchase/order/150038534231913?type=3', content=''),
            # Post(category='Chip', title='title', image='https://shopee.com.my/user/purchase/order/150038534231913?type=3', content=''),
            # Post(category='Chip', title='title', image='https://shopee.com.my/user/purchase/order/150038534231913?type=3', content=''),
            # Post(category='Chip', title='title', image='https://shopee.com.my/user/purchase/order/150038534231913?type=3', content=''),

            Post(category='Question', title='Dare', image='', content='I’ll pick a song and you have to give me a lap dance. Blindfolded.'),
            Post(category='Question', title='Dare', image='', content='You can’t say my name for the rest of the game, but instead, have to call me any nickname I choose. Every time you mess up, I get to spank you.'),
            Post(category='Question', title='Dare', image='', content='Go skinny dipping with me. (If you don’t have a private pool, get creative! The bathtub, shower, or a water fight in the kitchen all count.)'),
            Post(category='Question', title='Dare', image='', content='Try to literally (li li li) lick yourself from your head to your toes. '),
            Post(category='Question', title='Dare', image='', content='Kiss a part of my body you want to cum on.'),
            Post(category='Question', title='Dare', image='', content='Show me a video (an ~adult~ one, duh) of something you’d like us to try together.'),
            Post(category='Question', title='Dare', image='', content='You have one minute to turn me on using only your feet.'),
            Post(category='Question', title='Dare', image='', content='Imitate what I sound like when I orgasm.'),
            Post(category='Question', title='Dare', image='', content='Blindfold me and write something sexy on my body in lipstick.'),
            Post(category='Question', title='Dare', image='', content='Host a sexy, five-minute yoga class for me with lots of sensual stretching and downward dogging.'),
            Post(category='Question', title='Dare', image='', content='Describe my in-bed personality in three words.'),
            Post(category='Question', title='Dare', image='', content='If I were handcuffed to the bed, what would you do to me?'),
            Post(category='Question', title='Dare', image='', content='If we could only have sex in one position for a month, what position would you pick?'),
            Post(category='Question', title='Dare', image='', content='What sex move of mine is your favorite? Give me all the dirty details about why you like it.'),
            Post(category='Question', title='Dare', image='', content='What item of clothing do you think I look sexiest in?'),
            Post(category='Question', title='Dare', image='', content='Which is your favorite kind of sex: soft, slow, and sweet or aggressive, fast, and feisty?'),
            Post(category='Question', title='Dare', image='', content='Do you like being nibbled on or lightly bitten? Where?'),
            Post(category='Question', title='Dare', image='', content='What is your favorite body part for me to suck on?'),
            Post(category='Question', title='Dare', image='', content='Where is the strangest place you’ve ever masturbated?'),
            Post(category='Question', title='Dare', image='', content='What’s #1 on your sexual bucket list right now?'),
            Post(category='Question', title='Dare', image='', content='What sexual activity (or activities) do you think is underrated?'),
            Post(category='Question', title='Dare', image='', content='What do you want me to say while we are having sex?'),
            Post(category='Question', title='Dare', image='', content='What’s your favorite sex position?'),
            Post(category='Question', title='Dare', image='', content='What did you think the first time you saw me naked?'),
            Post(category='Question', title='Dare', image='', content='Tell me what it is like to have sex with me.'),
            Post(category='Question', title='Dare', image='', content='What do I do that really turns you on?'),
            Post(category='Question', title='Dare', image='', content='How long would your ideal quickie last? Describe every detail to me.'),
            Post(category='Question', title='Dare', image='', content='Would you rather have morning sex or night sex?'),
            Post(category='Question', title='Dare', image='', content='Kiss me upside down like Mary Jane kissed Spiderman.'),
            Post(category='Question', title='Dare', image='', content='With your tongue, write a word that describes me on my back.'),
            Post(category='Question', title='Dare', image='', content='Pick up my finger or hand and show me how you like to receive oral sex.'),
            Post(category='Question', title='Dare', image='', content='Kiss me anywhere you want.'),
            Post(category='Question', title='Dare', image='', content='Give me a 30-second lap dance'),
            Post(category='Question', title='Dare', image='', content='Use your fingers to trace over your favorite parts of my body.'),
            Post(category='Question', title='Dare', image='', content='Lick my back and form a word you want me to guess.'),
            Post(category='Question', title='Dare', image='', content='Suck on my belly button.'),
            Post(category='Question', title='Dare', image='', content='Kiss your way down my back or stomach.'),
            Post(category='Question', title='Dare', image='', content='Massage me with oil any way you choose for 30 seconds.'),
            Post(category='Question', title='Dare', image='', content='Snuggle me how you like for 20 seconds.'),
            Post(category='Question', title='Dare', image='', content='Stimulate two parts of my body at once. Use your hands on one part and your lips on the other.'),

            Post(category='Question', title='Dare', image='', content='Show me the part of your body that you think I find the sexiest.'),
            Post(category='Question', title='Dare', image='', content='Wear heels during foreplay or sex.'),
            Post(category='Question', title='Dare', image='', content='Use a scarf or your hair to lightly rub across your husband’s naked body.'),
            Post(category='Question', title='Dare', image='', content='Bring your husband to orgasm using a part of your body you’ve never used before, like your breasts or legs.'),
            Post(category='Question', title='Dare', image='', content='Use your teeth to gently nibble his nipples, earlobes, or other erogenous zones.'),
            Post(category='Question', title='Dare', image='', content='Remove one piece at a time while playing a song.'),
            Post(category='Question', title='Dare', image='', content='Both of you pick a piece of clothing and spray it with your favorite scent'),

            Post(category='Oral', title='Sideways Oral', image='https://hips.hearstapps.com/hmg-prod/images/3-the-sideways-oral-646e7a1530fe0.jpg?crop=1xw:1xh;center,top&resize=980:*', content=''),
            Post(category='Oral', title='The Chin Dildo', image='https://hips.hearstapps.com/hmg-prod/images/1-the-chin-dildo-1660751301.jpg?crop=1xw:1xh;center,top&resize=980:*', content=''),
            Post(category='Oral', title='Tantric Oral', image='https://hips.hearstapps.com/hmg-prod/images/2-the-tantric-oral-1660751363.jpg?crop=1xw:1xh;center,top&resize=980:*', content=''),
            Post(category='Oral', title='The Face Time', image='https://hips.hearstapps.com/hmg-prod/images/24-the-facetime-1-1603306465.jpg?crop=1xw:1xh;center,top&resize=980:*', content=''),
            Post(category='Oral', title='Weak in the Knees', image='https://hips.hearstapps.com/hmg-prod/images/26-week-in-the-knees-1603306460.jpg?crop=1xw:1xh;center,top&resize=980:*', content='Tease them a little first by kneeling down and mouthing the outside of their underwear, breathing your warm breath onto them, and kissing and sucking them through the fabric. Keep it up until they beg you to remove them'),
            Post(category='Oral', title='The Shark Fin', image='https://hips.hearstapps.com/hmg-prod/images/4-the-shark-fin-1603306709.jpg?crop=1xw:1xh;center,top&resize=980:*', content=''),
            Post(category='Oral', title='The Butterball', image='https://hips.hearstapps.com/hmg-prod/images/5-the-butterball-1603306738.jpg?crop=1xw:1xh;center,top&resize=980:*', content=''),
            Post(category='Oral', title='The Deep Sea Diver', image='https://hips.hearstapps.com/hmg-prod/images/6-the-deep-sea-diver-1603306766.jpg?crop=1xw:1xh;center,top&resize=980:*', content=''),
            Post(category='Oral', title='The Swiper', image='https://hips.hearstapps.com/hmg-prod/images/12-the-swiper-1603306935.jpg?crop=1xw:1xh;center,top&resize=980:*', content=''),
            Post(category='Oral', title='The Leg Up', image='https://hips.hearstapps.com/hmg-prod/images/21-the-leg-up-1603307158.jpg?crop=1xw:1xh;center,top&resize=980:*', content=''),
            Post(category='Oral', title='The Spiderman', image='https://hips.hearstapps.com/hmg-prod/images/23-the-spiderman-1603307212.jpg?crop=1xw:1xh;center,top&resize=980:*', content=''),


            Post(category='Positions', title='Stand and Deliver', content='Also known as: The Bicycle', image='https://hips.hearstapps.com/hmg-prod/images/men-shealth-stand-deliver-1581102532.jpg?resize=980:*'),
            Post(category='Positions', title='Pearly Gates', content='Great for G-spot stimulation.', image='https://hips.hearstapps.com/hmg-prod/images/pearly-gates-2-1650381834.jpg?resize=980:*'),
            Post(category='Positions', title='The Socket', content='content', image='https://hips.hearstapps.com/hmg-prod/images/men-shealth-thesocket-1581101518.jpg?resize=980:*'),
            Post(category='Positions', title='Standing O', content='', image='https://hips.hearstapps.com/hmg-prod/images/menshealth-standingo-1581101725.jpg?resize=640:*'),
            Post(category='Positions', title='The 69 Bridge', content='', image='https://hips.hearstapps.com/hmg-prod/images/men-shealth-69-bridge-v2-1582129462.jpg?resize=980:*'),
            Post(category='Positions', title='Waterfall', image='https://hips.hearstapps.com/hmg-prod/images/men-shealth-thewaterfall-1581101948.jpg?resize=980:*', content=''),
            Post(category='Positions', title='One Up', image='https://hips.hearstapps.com/hmg-prod/images/men-shealth-oneup-v2-1581101983.jpg?resize=980:*', content=''),
            Post(category='Positions', title='The Hot Seat', image='https://hips.hearstapps.com/hmg-prod/images/men-shealth-hotseat-1581102043.jpg?resize=640:*', content=''),
            Post(category='Positions', title='Stairway to Heaven', image='https://hips.hearstapps.com/hmg-prod/images/menshealth-stairwaytoheaven-1581102102.jpg?resize=980:*', content=''),
            Post(category='Positions', title='Pole Position', image='https://hips.hearstapps.com/hmg-prod/images/menshealth-poleposition-1581102164.jpg?resize=980:*', content=''),
            Post(category='Positions', title='The Lazy Man', image='https://hips.hearstapps.com/hmg-prod/images/menshealth-lazyman-1581102217.jpg?resize=980:*', content=''),
            Post(category='Positions', title='David Copperfield', image='https://hips.hearstapps.com/hmg-prod/images/menshealth-davidscopperfield-1581102244.jpg?resize=980:*', content=''),
            Post(category='Positions', title='Doggy Style', image='https://hips.hearstapps.com/hmg-prod/images/menshealth-mansbestfriend-v2-1581102405.jpg?resize=980:*', content=''),
            Post(category='Positions', title='The Flatiron', image='https://hips.hearstapps.com/hmg-prod/images/men-shealth-flatiron-v2-1581102438.jpg?resize=980:*', content=''),
            Post(category='Positions', title='Butter Churner', image='https://hips.hearstapps.com/hmg-prod/images/menshealth-butterchurner-1581102466.jpg?resize=640:*', content=''),
            Post(category='Positions', title='Wheelbarrow, Standing', image='https://hips.hearstapps.com/hmg-prod/images/menshealth-standingwheelbarrow-v2-1581102781.jpg?resize=640:*', content=''),
            Post(category='Positions', title='Restroom Attendant', image='https://hips.hearstapps.com/hmg-prod/images/menshealth-bathroomattendant-v2-1581102921.jpg?resize=640:*', content=''),
            Post(category='Positions', title='Couch Surfer', image='https://hips.hearstapps.com/hmg-prod/images/menshealth-couchsurfer-1581102970.jpg?crop=1.00xw:0.701xh;0,0.120xh&resize=640:*', content=''),
            Post(category='Positions', title='Open-Legged Spoon', image='https://hips.hearstapps.com/hmg-prod/images/open-legged-spoon-3-1650382204.jpg?resize=980:*', content=''),
            Post(category='Positions', title='The Fusion', image='https://hips.hearstapps.com/hmg-prod/images/menshealth-thefusion-1581103569.jpg?resize=980:*', content=''),
            Post(category='Positions', title='The Spider', image='https://hips.hearstapps.com/hmg-prod/images/menshealth-thespider-v2-1581103598.jpg?resize=980:*', content=''),
            Post(category='Positions', title='Hovering Butterfly', image='https://hips.hearstapps.com/hmg-prod/images/menshealth-hoveringbutterfly-1581103629.jpg?resize=980:*', content=''),
            Post(category='Positions', title='69', image='https://hips.hearstapps.com/hmg-prod/images/men-shealth-sexillustration-inverted-edit-1581103938.jpg?resize=980:*', content=''),

            Post(category='Positions', title='ACCORDION', image='https://amisdiaries.com/wp-content/uploads/2019/05/20190521_174131192822549.png', content=''),
            Post(category='Positions', title='AIRPLANE', image='https://amisdiaries.com/wp-content/uploads/2019/05/20190521_183022.png', content=''),
            Post(category='Positions', title='AMPHIBIAN', image='https://amisdiaries.com/wp-content/uploads/2019/05/20190521_1755561927245020.png', content=''),
            Post(category='Positions', title='AQUARIUS', image='https://amisdiaries.com/wp-content/uploads/2019/05/20190521_175213645520598.png', content=''),
            Post(category='Positions', title='', image='https://amisdiaries.com/wp-content/uploads/2019/05/20190521_173451587964785.png', content=''),
            Post(category='Positions', title='', image='https://amisdiaries.com/wp-content/uploads/2019/05/20190521_1753297332391.png', content=''),
            Post(category='Positions', title='', image='https://amisdiaries.com/wp-content/uploads/2019/05/20190521_175127782063318.png', content=''),
            Post(category='Positions', title='', image='https://amisdiaries.com/wp-content/uploads/2019/05/20190521_1744351648391560.png', content=''),
            Post(category='Positions', title='', image='https://amisdiaries.com/wp-content/uploads/2019/05/20190521_1737432082143707.png', content=''),
            Post(category='Oral', title='', image='https://amisdiaries.com/wp-content/uploads/2019/05/20190521_1728151707918502.png', content=''),
            Post(category='Positions', title='', image='https://amisdiaries.com/wp-content/uploads/2019/05/20190521_1722111829153546.png', content=''),
            Post(category='Positions', title='', image='https://amisdiaries.com/wp-content/uploads/2019/05/20190521_195256.png', content=''),
            Post(category='Positions', title='', image='https://amisdiaries.com/wp-content/uploads/2019/05/20190521_200408.png', content=''),
            Post(category='Positions', title='', image='https://amisdiaries.com/wp-content/uploads/2019/05/20190521_182618.png', content=''),
            Post(category='Oral', title='', image='https://amisdiaries.com/wp-content/uploads/2019/05/20190521_1727331873933845.png', content=''),
            Post(category='Positions', title='', image='https://amisdiaries.com/wp-content/uploads/2019/05/20190521_194441.png', content=''),
            Post(category='Positions', title='', image='https://amisdiaries.com/wp-content/uploads/2019/05/20190521_194159.png', content=''),
            Post(category='Positions', title='', image='https://amisdiaries.com/wp-content/uploads/2019/05/20190521_200015.png', content=''),
            Post(category='Positions', title='', image='https://amisdiaries.com/wp-content/uploads/2019/05/20190521_1738471649556942.png', content=''),
            Post(category='Positions', title='', image='https://amisdiaries.com/wp-content/uploads/2019/05/20190521_1745581239590505.png', content=''),
            Post(category='Positions', title='', image='https://amisdiaries.com/wp-content/uploads/2019/05/20190521_172951202764004.png', content=''),
            Post(category='Oral', title='', image='https://sexpositions.club/wp-content/uploads/2019/07/18_75.png', content=''),
            Post(category='Oral', title='', image='https://sexpositions.club/wp-content/uploads/2019/06/17_43.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2019/06/19_35.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2019/06/18_35.png', content=''),
            Post(category='Oral', title='', image='https://sexpositions.club/wp-content/uploads/2019/06/12_2_4.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2019/06/16_22.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2019/06/16_20.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2019/06/15_13.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2019/06/16_23.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2019/06/2_4_5.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2019/06/16_17.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2019/06/14_17.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2019/06/16_13.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2019/06/17_11.png', content=''),
            Post(category='Oral', title='', image='https://sexpositions.club/wp-content/uploads/2019/06/11_6.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2019/06/18_64.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2019/06/3_51_7.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2019/06/3_51_9.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2019/06/1_14_4.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2019/06/19_11.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2019/06/16_5.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2019/06/2_31.png', content=''),
            Post(category='Oral', title='', image='https://sexpositions.club/wp-content/uploads/2019/06/11_22_5.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2016/04/8_32.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2016/04/13_28.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2016/03/8_25_3.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2016/03/8_17_4.png', content=''),
            Post(category='Positions', title='', image='https://sexpositions.club/wp-content/uploads/2016/03/8_16_4.png', content=''),
            # Post(category='Positions', title='', image='', content=''),
            




            
            # Post(category='Positions', title='', image='', content=''),


        ]
        Post.objects.bulk_create(objects_to_create)
