# Generated by Django 4.0.6 on 2022-08-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="title",
            options={"verbose_name": "Title"},
        ),
        migrations.AddField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[("STUDENT", "STUDENT"), ("LIBRARIAN", "LIBRARIAN")],
                default="STUDENT",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
