# Generated by Django 4.0.6 on 2022-08-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_title_number_available"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booktracking",
            old_name="user",
            new_name="student",
        ),
    ]
