# Generated by Django 4.0.6 on 2022-08-28 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_user_booktracking_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="booktracking",
            name="librarian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="libratian_tracking",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="booktracking",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_tracking",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
