# Generated by Django 4.0.6 on 2022-08-28 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_booktracking_book_alter_booktracking_librarian_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booktracking",
            name="is_return",
            field=models.BooleanField(default=False, verbose_name="Is return"),
        ),
        migrations.AlterField(
            model_name="booktracking",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.book"
            ),
        ),
    ]
